### ISSUE TITLE
hackurba - increment version to 1.2-SNAPSHOT

### ISSUE THREAD

**Issue by mborne** [IGNF/simplu3D-rules#4]
simplu3D-rules, simplu3D & co

**Comment by mbrasebin** [comment]
Tu penses que ça vaut vraiment le coup ? Si j'intègre bien ce qui a été développé ce week end, il ne devrait pas y avoir de soucis.

**Comment by mbrasebin** [comment]
Done and merged in : 7ef3fe2
Modification will be pushed in projects using SimPLU3D-rules
